[package]
authors = ["Without Boats <woboats@gmail.com>"]
name = "rigging"
version = "0.1.0"

[dependencies]
futures = "0.1.11"
tokio-service = "0.1.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
