[package]
authors = ["Without Boats <woboats@gmail.com>"]
build = "build.rs"
name = "compass-rose"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.12.0"

[dependencies]
itertools = "0.5.6"
lalrpop-util = "0.12.0"
