[package]
name = "mainsail"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]

[dependencies]
futures = "0.1.13"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

[dependencies.rigging]
path = "../rigging"
